title: Kevin Freire # your name (or website title) here
logo: "/images/kevin_logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a data scientist with over 2 years of experience 
  in machine learning and data analysis. With a Masters 
  degree in Computer Engineering from Toronto Metropolitan 
  University.
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
